# syntax=docker/dockerfile:1
FROM python:3.7-alpine
WORKDIR /code
ENV FLASK_APP=test/app.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY test/requirements.txt requirements.txt
RUN pip install -U  --upgrade pip
RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
CMD ["flask", "run"]