FROM screenly/srly-ose-base

RUN mkdir -p /usr/src/app
COPY . /usr/src/app/
WORKDIR /usr/src/app
COPY requirements/requirements.txt /usr/src/app/requirements/
RUN pip install --no-cache-dir -r /usr/src/app/requirements/requirements.txt

ARG GIT_HASH
ENV GIT_HASH=$GIT_HASH
ARG GIT_SHORT_HASH
ENV GIT_SHORT_HASH=$GIT_SHORT_HASH
ARG GIT_BRANCH
ENV GIT_BRANCH=$GIT_BRANCH

CMD ["bash", "bin/start_server.sh"]
